### ISSUE TITLE
"About" section

### ISSUE THREAD

**Issue by timcallow** [atomec-project/atoMEC#14]
I have added a short description (taken directly from the `README`) and a few suggested topics. @acangi feel free to make any changes you would like.

![about_atoMEC](https://user-images.githubusercontent.com/18050753/123436323-cc26b480-d5ce-11eb-97a8-e9c2c2bf271d.png)

**Comment by DanielKotik** [comment]
@timcallow  I think we can close this issue since @acangi  and me are fine with it.
