### ISSUE TITLE
Test workflow warnings

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/atoMEC#165]
Some warnings appear in new test workflow:

![image](https://user-images.githubusercontent.com/28047702/197410819-c3235b0c-6451-4df1-a958-a7945427554a.png)

![image](https://user-images.githubusercontent.com/28047702/197410915-746a94ce-dd80-4ca9-b610-ebf42eaf6e8c.png)

- your are using a rather old version of the [cache action](https://github.com/actions/cache) (v1 instead of v3), an update should resolve some of the above issues
- change `runs-on: ubuntu-18.04` to a more recent version

**Comment by timcallow** [comment]
Mm yes, also the same in the docs workflow

![Screenshot 2022-10-23 at 21 08 28](https://user-images.githubusercontent.com/18050753/197415757-425a124f-d13b-4b56-a797-97dcd36e6dd9.png)

I'll make the same changes there too, unless there's a reason not to?

**Comment by DanielKotik** [comment]
Go for it! :)

**Comment by timcallow** [comment]
Closing as this was fixed some time ago
