### ISSUE TITLE
PyPI badge does not update to recent version - automate clearing the cache?

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/atoMEC#167]
This issue is related to GitHub caching badges. This issue can be solved as described [here](https://dev.to/jcubic/github-action-to-clear-cache-on-images-in-readme-5g1n)

For example, in Chromium open [README.md](https://github.com/atomec-project/atoMEC/blob/develop/README.md) and use the Web Developer Tools to inspect the badge in order to retrieve the respective https://camo.gitubusercontent... URL, see

![image](https://user-images.githubusercontent.com/28047702/204498222-ee0702a4-0c63-4c1a-affe-c797f721277e.png)

Now clear the cache with `curl -w "\n" -s -X PURGE https://camo.githubusercontent.com/..`

**Comment by timcallow** [comment]
I'm closing this as the correct version displays eventually, it just takes some time (or a manual clearing of the cache)
