### ISSUE TITLE
`__init__` methods do not get parsed by Sphinx autodoc

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/atoMEC#26]
> > Looks good.
> > I think the docstring in `models.ISModel` is not rendering correctly due to some incorrect formatting... But even if it were rendering there would the same error as we saw in PRs #18 and #16. I will fix later today.
> 
> Mhh, for me this docsting looks good. Also, there are now warning messages anymore.

Strange there are no warnings, but I don't see any of the class parameters displaying? And the `property`s have no docs

![Screenshot from 2021-06-28 12-02-10](https://user-images.githubusercontent.com/18050753/123619067-17c4a280-d809-11eb-8185-3cb0627ccfbb.png)

_Originally posted by @timcallow in https://github.com/atomec-project/atoMEC/issues/19#issuecomment-869554059_

**Comment by timcallow** [comment]
@DanielKotik I'm not sure we want  `__init__` methods to be parsed. In other parts of the code I used the convention of documenting not inside `__init__` but rather directly after the class first line. I think it would be better to modify the `ISModel` class to reflect the convention elsewhere and it will all work out (actually I already started doing this locally, will push soon...)

**Comment by DanielKotik** [comment]
Yeah, this is the easiest solution. It is also more reasonable to do it within the class docstring as we have done it at some other classes already - being consistent is a good thing. Attributes, however, may still be documented inline, i.e. within the `__init__` method as demonstrated [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html). While having a docstring of `__init__` if fully compliant with Numpy's docstring style convention, Sphinx autodoc seems to treat `__init__` magic methods special - sure for good reason (I will figure out why).

**Comment by DanielKotik** [comment]
Setting `autoclass_content` to  `"both"` in `conf.py`  concatenates the class’ and the ` __init__` method’s docstring. It is somehow weird to set this explicitly, because [here](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) Sphinx docs says _...Sphinx’s default behavior, which considers the `__init__` docstring as part of the class documentation._

![grafik](https://user-images.githubusercontent.com/28047702/124240722-4f8a5d80-db1b-11eb-86f9-8b384a52f0db.png)

However, as we already agreed on documenting the parameters directly inside the class docstring, I will leave it as is.

**Comment by DanielKotik** [comment]
@timcallow You can close this issue, when you have read my above comment.
