### ISSUE TITLE
Black: line length formatting fails for docstrings!?

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/atoMEC#29]
Black sets line lengths to 88 by default (PEP8 recommends however a line length of 79 characters). Either way, I have noticed that black does not reformat docstrings to adjust the line length.  @timcallow can you confirm this? If we have to manually adjust the line length for docstrings, I would suggest to use flake8/pycodestyle to check against it (also in the pipeline).

We first have to agree on the number of characters per line (I am fine with both 79 and 88, but not more). If this differs from black's default, we should add a `pyproject.toml` with

```toml
[tool.black]
line-length = 79
```

**Comment by timcallow** [comment]
Yes, this was bothering me. I've been looking to see if there is an option to enforce this but so far I didn't find anything. If you have an alternative suggestion to `black`, I'm happy to consider it.

In any case I don't mind the line length, if we stick with `black` I'd lean slightly towards 88 but otherwise I don't have a preference.

**Comment by DanielKotik** [comment]
OK, then we shall add a `.flake8` configuration file with
```
[flake8]
max-line-length = 88
extend-ignore = E203
```
as suggested by black's documentation and use `flake8` in our IDE (I do so already) and within the CI. This would point us to where we need to manually do some adjustments for docstrings.

**Comment by timcallow** [comment]
Closing due to PR #30

**Comment by DanielKotik** [comment]
Note:

Black can split long strings to [fit the line length](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html?highlight=experimental#improved-string-processing) using `--experimental-string-processing`. However, this applies [not (yet) to docstrings](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#labels-experimental-string).
