### ISSUE TITLE
Clash between `pydocstyle` errors and `property` documentation

### ISSUE THREAD

**Issue by timcallow** [atomec-project/atoMEC#37]
Running `pydocstyle --convention=numpy <file.py>` produces errors such as:

```
staticKS.py:523 in public method `E_xc`:
        D401: First line should be in imperative mood; try rephrasing (found 'dict')
staticKS.py:523 in public method `E_xc`:
        D403: First word of the first line should be properly capitalized ('Dict', not 'dict')
```

which clash (especially the first error) with how we document `property` tags (which follows the advice in https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html).

**Comment by DanielKotik** [comment]
On this imperative mood thing with regards to properties there is an ongoing discussion: https://github.com/PyCQA/pydocstyle/issues/301

If you follow strictly the rules defined in https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html then there is no clash. Change (please note capitalised `The ...`)

```diff
-"""dict of floats: the xc energy, containing keys `x`, `c` and `xc`
-        for exchange, correlation and exchange + correlation respectively"""
+""":obj:`dict` of :obj:`float`: The xc energy.
+
+Contains keys `x`, `c` and `xc` for exchange, correlation and
+exchange + correlation respectively.
+"""
```

**Comment by timcallow** [comment]
Ok thanks for clarifying that and see PR #16.

For consistency I would prefer to go with non-imperative docstrings if you agree.
