### ISSUE TITLE
Version number in `setup.py` vs `CITATION.cff`

### ISSUE THREAD

**Issue by timcallow** [atomec-project/atoMEC#66]
In `setup.py` the version is given as `0.1.0`, whereas in `CITATION.cff` it is `1.0.0`. Should we make these consistent? @DanielKotik I defer to your judgement on which is more appropriate.

(Also, I'm the only author listed in `setup.py`. I guess this ok since we can't list everyone there)

**Comment by DanielKotik** [comment]
Good catch. I noticed this already and will change this. The version given in `setup.py` is important when publishing via PyPi. Of course, all version numbers should be equal, best case is "a single source of truth" - one place where the version is set.
